server:
  port: 8082  # ???????????

spring:
  application:
    name: catalog-service  # ?????? Docker ?????
  datasource:
    url: jdbc:mysql://localhost:3306/enrollment_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root  # ?? MySQL ????????
    password: 123456  # ????
  jpa:
    hibernate:
      ddl-auto: update  # ??????????????
    show-sql: true  # ?? SQL ???????
    properties:
      hibernate:
        format_sql: true  # ??? SQL ??
# catalog-service??????????localhost:8081?Docker?????http://catalog-service:8081?{insert\_element\_16\_}?
catalog-service:
  url: http://localhost:8081