server:
  port: 8081  # ???????????

spring:
  application:
    name: catalog-service  # ?????? Docker ?????
  datasource:
    url: jdbc:mysql://localhost:3306/catalog_log?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root  # ?? MySQL ????????
    password: 123456  # ????
  jpa:
    hibernate:
      ddl-auto: update  # ??????????????
    show-sql: true  # ?? SQL ???????
    properties:
      hibernate:
        format_sql: true  # ??? SQL ??